config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "lists#index"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  has_one_attached :photo
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list, message: 'Association should be unique !' }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list_id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path(@bookmark.list_id), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Add a movie</h1>


<%= simple_form_for(@bookmark, as: :bookmark, method: :post, url: list_bookmarks_path) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Add a movie to my list", class:"btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://digitalcine.b-cdn.net/wp-content/uploads/2020/12/la-haine-kassovitz-edition-studiocanal-2020-master4k-capture-blu-ray-4k-ultra-hd-04.jpg);">
  <div class="container">
    <h1>My movie List !</h1>
    <p>Here you can find the bests movies on earth...</p>
  </div>
</div>
<div class="container col-6 my-5">
<h1 class="align-center">ALL THE LISTS</h1>

<ul class="list-group">
  <% @lists.each do |list| %>
      <li class="list-group-item">
        <% if list.photo.attached? %>
          <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
            <%= cl_image_tag "Filmandclapboard_jdlyez", height: 300, width: 400, crop: :fill %>
        <% end %>
      </li>
    <%= link_to list.name, list_path(list.id)%>
  <% end %>
</ul>

<%= link_to "Add a new list", new_list_path(@list)%>

</div>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= simple_form_for [@list] do |l| %>
  <%= l.input :name %>
  <%= l.input :photo, as: :file %>
  <%= l.submit "Submit list", class: "btn btn-primary" %>
<% end %>

<%= link_to "See all lists", lists_path(@list)%>

app/views/lists/show.html.erb
<div class="container">
<h1><%= @list.name %></h1>

<h2><%@list.movies.each do |m|%>
    <div class="card-product">
        <%= image_tag "#{m.poster_url}" %>
          <div class="card-product-infos">
            <h2><%= m.title%></h2>
            <p><%= m.overview%></p>
            <p><%= m.rating%></p>
            <% bookmark = Bookmark.find_by(movie: m, list: @list)%>
              <p><%= link_to "Delete",
              bookmark_path(bookmark),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
            %></p>
          </div>
        </h2>
      <%end%>
    </div>
    <%= link_to "See all lists", lists_path(@list)%>
    <%= link_to "Add a movie to my list", new_list_bookmark_path(@list)%>
</div>